title: "Logboek"
# author: "Default Author Name"
description: "Voor wie het lezen wil"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

theme: "minima"

rss: rss

show_excerpts: true

excerpt_separator: <!--more-->
