title: "Logboek"
author: "fp"
description: "Voor wie het lezen wil"

rss: rss
show_excerpts: true
excerpt_separator: <!--more-->

theme: minima

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up

header_pages:
 - about.md
 - reparaties.md

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root
